# Generated by Django 4.1.2 on 2022-10-22 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('height', models.PositiveIntegerField()),
                ('mass', models.PositiveIntegerField()),
                ('hair_color', models.CharField(max_length=150)),
                ('skin_color', models.CharField(max_length=150)),
                ('eye_color', models.CharField(max_length=150)),
                ('birth_year', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
