# Generated by Django 4.1.2 on 2022-10-22 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('characters', '0001_initial'),
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='home_world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planets.planet'),
        ),
        migrations.AddField(
            model_name='people',
            name='movies',
            field=models.ManyToManyField(to='movies.movie'),
        ),
    ]
