# Generated by Django 3.1 on 2022-10-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20221025_0344'),
        ('characters', '0004_auto_20221025_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='movies',
            field=models.ManyToManyField(null=True, to='movies.Movie'),
        ),
    ]
