# Generated by Django 4.1.2 on 2022-10-22 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('diameter', models.PositiveIntegerField()),
                ('climate', models.CharField(max_length=20)),
                ('gravity', models.FloatField()),
                ('terrain', models.CharField(max_length=20)),
                ('population', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('movies', models.ManyToManyField(to='movies.movie')),
            ],
        ),
    ]
