# Generated by Django 3.1 on 2022-10-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0002_auto_20221024_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='climate',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='planet',
            name='terrain',
            field=models.CharField(max_length=150),
        ),
    ]
