# Generated by Django 3.1 on 2022-10-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0003_auto_20221025_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='movies',
        ),
        migrations.AlterField(
            model_name='planet',
            name='diameter',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.PositiveBigIntegerField(),
        ),
    ]
