# Generated by Django 3.1 on 2022-10-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0004_auto_20221025_0344'),
        ('movies', '0003_auto_20221024_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='opening_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='planets',
            field=models.ManyToManyField(to='planets.Planet'),
        ),
    ]
